import React, { createContext, useContext, useState, ReactNode } from 'react';

export interface Language {
  code: string;
  name: string;
  flag: string;
}

export const languages: Language[] = [
  { code: 'KR', name: '한국어', flag: '🇰🇷' },
  { code: 'EN', name: 'English', flag: '🇺🇸' },
  { code: 'CH', name: '中文', flag: '🇨🇳' },
  { code: 'JP', name: '日本語', flag: '🇯🇵' }
];

interface LanguageContextType {
  currentLanguage: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// 다국어 텍스트 데이터
const translations = {
  KR: {
    'nav.home': '홈',
    'nav.about': '소개',
    'nav.treatments': '치료',
    'nav.event': '이벤트',
    'nav.contact': '연락처',
    'nav.book': '예약',
    'nav.dashboard': '대시보드',
    'nav.services': '서비스',
    'footer.copyright': '© 2024 SoRa Clinic. 모든 권리 보유.',
    'footer.description': '아름다움을 위한 최고의 선택',
    'home.hero.title': 'SoRa Clinic에 오신 것을 환영합니다',
    'home.hero.subtitle': '당신의 아름다움을 위한 전문적인 케어',
    'home.hero.bookNow': '지금 예약하기',
    'about.title': 'SoRa Clinic 소개',
    'about.subtitle': '우리는 진정한 글래스 스킨 경험을 제공하는 열정적인 K-뷰티 전문가입니다. 한국 스킨케어 전통에 대한 수년간의 전문성과 탁월성에 대한 헌신으로 모든 치료를 특별하게 만듭니다.',
    'about.journey.title': '우리의 뷰티 여정',
    'about.team.title': '뷰티 전문가들을 만나보세요',
    'about.timeline.2018.title': 'SoRa Clinic 설립',
    'about.timeline.2018.desc': '글로벌 고객에게 진정한 K-뷰티 치료를 제공한다는 비전으로 SoRa Clinic이 설립되었습니다.',
    'about.timeline.2019.title': '첫 번째 글래스 스킨 치료',
    'about.timeline.2019.desc': '한국 뷰티 표준을 국제적으로 선도하는 시그니처 글래스 스킨 치료를 도입했습니다.',
    'about.timeline.2020.title': '뷰티 혁신',
    'about.timeline.2020.desc': '팬데믹 기간 동안 홈 스킨케어 상담에 중점을 둔 고급 보습 치료를 개발했습니다.',
    'about.timeline.2022.title': '팀 확장',
    'about.timeline.2022.desc': '전문 K-뷰티 전문가를 포함한 팀을 확장하고 강남 플래그십 클리닉을 오픈했습니다.',
    'about.timeline.2024.title': '글로벌 인정',
    'about.timeline.2024.desc': '"최고의 K-뷰티 클리닉"상을 수상하고 시그니처 치료를 국제적으로 확장했습니다.',
    'treatments.title': '치료 서비스',
    'treatments.subtitle': 'SoRa Clinic 전문가들의 전문 K-뷰티 치료, 스킨케어 솔루션 및 전문 서비스',
    'treatments.post1.title': '궁극의 K-뷰티 루틴: 글래스 스킨을 위한 10단계',
    'treatments.post1.excerpt': '전통적인 K-뷰티 방법을 통해 그 갈망하는 글래스 스킨 글로우를 달성하는 포괄적인 가이드로 한국 스킨케어의 비밀을 발견하세요.',
    'treatments.post2.title': '글래스 스킨 vs 듀이 스킨: 차이점 이해하기',
    'treatments.post2.excerpt': '글래스 스킨과 듀이 스킨의 뉘앙스를 배우고, 어떤 한국 뷰티 트렌드가 당신의 피부 타입과 목표에 적합한지 발견하세요.',
    'treatments.post3.title': '보습 히어로: 건성 피부를 위한 최고의 한국 성분',
    'treatments.post3.excerpt': '히알루론산부터 달팽이 점액까지, 깊은 보습을 위한 가장 효과적인 한국 스킨케어 성분을 탐험하세요.',
    'treatments.post4.title': '계절별 스킨케어: K-뷰티 루틴 적응하기',
    'treatments.post4.excerpt': '모든 계절에 건강하고 빛나는 피부를 유지하기 위해 일년 내내 한국 스킨케어 루틴을 수정하는 방법을 배우세요.',
    'treatments.post5.title': 'K-뷰티의 과학: 한국 스킨케어가 효과적인 이유',
    'treatments.post5.excerpt': '성분 혁신부터 레이어링 기술까지, 한국 스킨케어를 매우 효과적으로 만드는 과학적 원리를 깊이 파헤쳐보세요.',
    'treatments.post6.title': 'K-뷰티로 안티에이징: 예방 vs 교정 케어',
    'treatments.post6.excerpt': '한국식 안티에이징 스킨케어 접근 방식을 이해하고 기존 문제를 치료하면서 노화 징후를 예방하는 방법을 배우세요.',
    'event.title': '이벤트 및 프로모션',
    'event.subtitle': 'SoRa Clinic의 특별한 프로모션과 이벤트를 확인하세요',
    'event.promo1.title': '레이저 제모 패키지',
    'event.promo1.desc': '국제 환자를 위한 완전한 레이저 제모 패키지. 보장된 매끄럽고 아름다운 피부 결과를 위한 프리미엄 IPL 기술.',
    'event.promo2.title': '보톡스 안티에이징 치료',
    'event.promo2.desc': '젊고 주름 없는 피부를 위한 전문 보톡스 치료. 경험 많은 한국 미용 의사와 함께 FDA 승인 제품.',
    'event.promo3.title': '더말 필러 보강',
    'event.promo3.desc': '자연스러운 한국 뷰티 결과를 위한 얼굴 윤곽 및 볼륨 복원을 위한 프리미엄 히알루론산 필러.',
    'event.promo4.title': '글래스 스킨 페이셜 패키지',
    'event.promo4.desc': '도자기 같은 피부 톤을 달성하기에 완벽한 우리의 시그니처 보습 페이셜 치료로 유명한 한국 "글래스 스킨" 룩을 달성하세요.',
    'event.promo5.title': 'K-뷰티 글로우 치료',
    'event.promo5.desc': '빛나는 피부를 위한 LED 치료, 비타민 C 주입, 한국 브라이트닝 기술을 결합한 포괄적인 K-뷰티 글로우 프로그램.',
    'event.promo6.title': '프리미엄 스킨케어 루틴',
    'event.promo6.desc': '포괄적인 피부 변형과 안티에이징을 위한 여러 고급 치료를 결합한 궁극의 한국 뷰티 패키지.',
    'event.promo7.title': '보습 뷰티 부스트',
    'event.promo7.desc': '깊은 보습과 탄력 회복을 위한 고급 보습 치료.',
    'contact.title': '연락처',
    'contact.address': '6층, 123빌딩, 강남구, 서울, 한국',
    'contact.phone': '(+82)555-5555',
    'contact.email': 'Info@soraclinic.com',
    'contact.hours': '운영시간',
    'contact.hours.monFri': '월요일 - 금요일',
    'contact.hours.monFriTime': '오전 10:00 - 오후 8:00',
    'contact.hours.saturday': '토요일',
    'contact.hours.saturdayTime': '오전 10:00 - 오후 3:00',
    'contact.visitMessage': '원하시는 시간을 예약하신 후 방문해 주시기 바랍니다.',
    'booking.title': '예약하기',
    'booking.name': '이름',
    'booking.phone': '전화번호',
    'booking.email': '이메일',
    'booking.date': '예약 날짜',
    'booking.time': '예약 시간',
    'booking.service': '서비스 선택',
    'booking.submit': '예약 제출',
    'language.select': '언어 선택',
    'common.readMore': '더 보기',
    'common.learnMore': '자세히 보기',
    'common.bookNow': '지금 예약',
    'common.validUntil': '유효기간',
    'common.includes': '포함 사항',
    'common.category': '카테고리',
    'common.author': '작성자',
    'common.date': '날짜'
  },
  EN: {
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.treatments': 'Treatments',
    'nav.event': 'Event',
    'nav.contact': 'Contact',
    'nav.book': 'Book',
    'nav.dashboard': 'Dashboard',
    'nav.services': 'Services',
    'footer.copyright': '© 2024 SoRa Clinic. All rights reserved.',
    'footer.description': 'The best choice for beauty',
    'home.hero.title': 'Welcome to SoRa Clinic',
    'home.hero.subtitle': 'Professional care for your beauty',
    'home.hero.bookNow': 'Book Now',
    'about.title': 'About SoRa Clinic',
    'about.subtitle': 'We are passionate K-beauty experts dedicated to bringing you the authentic glass skin experience. With years of expertise in Korean skincare traditions and a commitment to excellence, we make every treatment extraordinary.',
    'about.journey.title': 'Our Beauty Journey',
    'about.team.title': 'Meet Our Beauty Experts',
    'about.timeline.2018.title': 'SoRa Clinic Founded',
    'about.timeline.2018.desc': 'SoRa Clinic was established with a vision to bring authentic K-beauty treatments to global clients.',
    'about.timeline.2019.title': 'First Glass Skin Treatment',
    'about.timeline.2019.desc': 'Introduced our signature Glass Skin treatment, pioneering Korean beauty standards internationally.',
    'about.timeline.2020.title': 'Beauty Innovation',
    'about.timeline.2020.desc': 'Developed advanced hydration therapies during the pandemic, focusing on at-home skincare consultations.',
    'about.timeline.2022.title': 'Team Expansion',
    'about.timeline.2022.desc': 'Grew our team to include specialized K-beauty experts and opened our Gangnam flagship clinic.',
    'about.timeline.2024.title': 'Global Recognition',
    'about.timeline.2024.desc': 'Received "Best K-Beauty Clinic" award and expanded our signature treatments internationally.',
    'treatments.title': 'Treatment Services',
    'treatments.subtitle': 'Expert K-beauty treatments, skincare solutions, and professional services from our SoRa Clinic specialists',
    'treatments.post1.title': 'The Ultimate K-Beauty Routine: 10 Steps to Glass Skin',
    'treatments.post1.excerpt': 'Discover the secrets of Korean skincare with our comprehensive guide to achieving that coveted glass skin glow through traditional K-beauty methods.',
    'treatments.post2.title': 'Glass Skin vs. Dewy Skin: Understanding the Difference',
    'treatments.post2.excerpt': 'Learn about the nuances between glass skin and dewy skin, and discover which Korean beauty trend is right for your skin type and goals.',
    'treatments.post3.title': 'Hydration Heroes: Best Korean Ingredients for Dry Skin',
    'treatments.post3.excerpt': 'Explore the most effective Korean skincare ingredients for deep hydration, from hyaluronic acid to snail mucin and beyond.',
    'treatments.post4.title': 'Seasonal Skincare: Adapting Your K-Beauty Routine',
    'treatments.post4.excerpt': 'Learn how to modify your Korean skincare routine throughout the year to maintain healthy, glowing skin in every season.',
    'treatments.post5.title': 'The Science Behind K-Beauty: Why Korean Skincare Works',
    'treatments.post5.excerpt': 'Dive deep into the scientific principles that make Korean skincare so effective, from ingredient innovation to layering techniques.',
    'treatments.post6.title': 'Anti-Aging with K-Beauty: Preventive vs. Corrective Care',
    'treatments.post6.excerpt': 'Understand the Korean approach to anti-aging skincare and learn how to prevent signs of aging while treating existing concerns.',
    'event.title': 'Events & Promotions',
    'event.subtitle': 'Check out special promotions and events from SoRa Clinic',
    'event.promo1.title': 'Laser Hair Removal Package',
    'event.promo1.desc': 'Complete laser hair removal package for international patients. Premium IPL technology with guaranteed smooth, beautiful skin results.',
    'event.promo2.title': 'Botox Anti-Aging Treatment',
    'event.promo2.desc': 'Professional Botox treatment for youthful, wrinkle-free skin. FDA-approved products with experienced Korean aesthetic doctors.',
    'event.promo3.title': 'Dermal Filler Enhancement',
    'event.promo3.desc': 'Premium hyaluronic acid fillers for facial contouring and volume restoration with natural-looking Korean beauty results.',
    'event.promo4.title': 'Glass Skin Facial Package',
    'event.promo4.desc': 'Achieve the famous Korean "glass skin" look with our signature hydrating facial treatment perfect for achieving porcelain-like complexion.',
    'event.promo5.title': 'K-Beauty Glow Treatment',
    'event.promo5.desc': 'Comprehensive K-beauty glow program combining LED therapy, vitamin C infusions, and Korean brightening techniques for luminous skin.',
    'event.promo6.title': 'Premium Skincare Routine',
    'event.promo6.desc': 'Ultimate Korean beauty package combining multiple advanced treatments for comprehensive skin transformation and anti-aging.',
    'event.promo7.title': 'Hydrating Beauty Boost',
    'event.promo7.desc': 'Advanced hydration therapy for deep moisturizing and elasticity restoration.',
    'contact.title': 'Contact Us',
    'contact.address': 'Address',
    'contact.phone': 'Phone',
    'contact.email': 'Email',
    'contact.hours': 'Business Hours',
    'booking.title': 'Book Appointment',
    'booking.name': 'Name',
    'booking.phone': 'Phone',
    'booking.email': 'Email',
    'booking.date': 'Appointment Date',
    'booking.time': 'Appointment Time',
    'booking.service': 'Select Service',
    'booking.submit': 'Submit Booking',
    'language.select': 'Select Language',
    'common.readMore': 'Read More',
    'common.learnMore': 'Learn More',
    'common.bookNow': 'Book Now',
    'common.validUntil': 'Valid until',
    'common.includes': 'Includes',
    'common.category': 'Category',
    'common.author': 'Author',
    'common.date': 'Date'
  },
  CH: {
    'nav.home': '首页',
    'nav.about': '关于',
    'nav.treatments': '治疗',
    'nav.event': '活动',
    'nav.contact': '联系',
    'nav.book': '预约',
    'nav.dashboard': '仪表板',
    'nav.services': '服务',
    'footer.copyright': '© 2024 SoRa Clinic. 保留所有权利。',
    'footer.description': '美丽的最佳选择',
    'home.hero.title': '欢迎来到SoRa Clinic',
    'home.hero.subtitle': '为您的美丽提供专业护理',
    'home.hero.bookNow': '立即预约',
    'about.title': '关于SoRa Clinic',
    'about.subtitle': '我们是热情的K-美容专家，致力于为您带来真正的玻璃肌肤体验。凭借多年韩国护肤传统专业知识和追求卓越的承诺，我们让每一次治疗都变得非凡。',
    'about.journey.title': '我们的美容之旅',
    'about.team.title': '认识我们的美容专家',
    'about.timeline.2018.title': 'SoRa Clinic成立',
    'about.timeline.2018.desc': 'SoRa Clinic成立，愿景是为全球客户带来真正的K-美容治疗。',
    'about.timeline.2019.title': '首次玻璃肌肤治疗',
    'about.timeline.2019.desc': '推出我们的标志性玻璃肌肤治疗，在国际上开创韩国美容标准。',
    'about.timeline.2020.title': '美容创新',
    'about.timeline.2020.desc': '在疫情期间开发先进的保湿疗法，专注于居家护肤咨询。',
    'about.timeline.2022.title': '团队扩展',
    'about.timeline.2022.desc': '扩大团队包括专业K-美容专家，并开设江南旗舰诊所。',
    'about.timeline.2024.title': '全球认可',
    'about.timeline.2024.desc': '获得"最佳K-美容诊所"奖，并在国际上扩展我们的标志性治疗。',
    'treatments.title': '治疗服务',
    'treatments.subtitle': '来自SoRa Clinic专家的专业K-美容治疗、护肤解决方案和专业服务',
    'treatments.post1.title': '终极K-美容程序：玻璃肌肤的10个步骤',
    'treatments.post1.excerpt': '通过我们通过传统K-美容方法实现令人向往的玻璃肌肤光泽的综合指南，发现韩国护肤的秘密。',
    'treatments.post2.title': '玻璃肌肤vs水润肌肤：理解差异',
    'treatments.post2.excerpt': '了解玻璃肌肤和水润肌肤之间的细微差别，发现哪种韩国美容趋势适合您的皮肤类型和目标。',
    'treatments.post3.title': '保湿英雄：干性皮肤的最佳韩国成分',
    'treatments.post3.excerpt': '探索从透明质酸到蜗牛粘液等深层保湿最有效的韩国护肤成分。',
    'treatments.post4.title': '季节性护肤：调整您的K-美容程序',
    'treatments.post4.excerpt': '学习如何全年修改您的韩国护肤程序，在每个季节保持健康、光彩照人的皮肤。',
    'treatments.post5.title': 'K-美容背后的科学：为什么韩国护肤有效',
    'treatments.post5.excerpt': '深入了解使韩国护肤如此有效的科学原理，从成分创新到分层技术。',
    'treatments.post6.title': 'K-美容抗衰老：预防vs矫正护理',
    'treatments.post6.excerpt': '了解韩国抗衰老护肤方法，学习如何在治疗现有问题的同时预防衰老迹象。',
    'event.title': '活动和促销',
    'event.subtitle': '查看SoRa Clinic的特别促销和活动',
    'event.promo1.title': '激光脱毛套餐',
    'event.promo1.desc': '国际患者完整的激光脱毛套餐。保证光滑、美丽皮肤效果的优质IPL技术。',
    'event.promo2.title': '肉毒杆菌抗衰老治疗',
    'event.promo2.desc': '年轻、无皱纹皮肤的专业肉毒杆菌治疗。经验丰富的韩国美容医生使用FDA批准的产品。',
    'event.promo3.title': '真皮填充剂增强',
    'event.promo3.desc': '用于面部轮廓和体积恢复的优质透明质酸填充剂，具有自然外观的韩国美容效果。',
    'event.promo4.title': '玻璃肌肤面部套餐',
    'event.promo4.desc': '通过我们完美实现瓷器般肤色的标志性保湿面部治疗，实现著名的韩国"玻璃肌肤"外观。',
    'event.promo5.title': 'K-美容光泽治疗',
    'event.promo5.desc': '结合LED治疗、维生素C注入和韩国提亮技术的综合K-美容光泽程序，打造发光肌肤。',
    'event.promo6.title': '优质护肤程序',
    'event.promo6.desc': '结合多种先进治疗的终极韩国美容套餐，实现全面的皮肤转变和抗衰老。',
    'event.promo7.title': '保湿美容提升',
    'event.promo7.desc': '用于深层保湿和弹性恢复的先进保湿治疗。',
    'contact.title': '联系我们',
    'contact.address': '地址',
    'contact.phone': '电话',
    'contact.email': '电子邮件',
    'contact.hours': '营业时间',
    'booking.title': '预约',
    'booking.name': '姓名',
    'booking.phone': '电话',
    'booking.email': '电子邮件',
    'booking.date': '预约日期',
    'booking.time': '预约时间',
    'booking.service': '选择服务',
    'booking.submit': '提交预约',
    'language.select': '选择语言',
    'common.readMore': '阅读更多',
    'common.learnMore': '了解更多',
    'common.bookNow': '立即预约',
    'common.validUntil': '有效期至',
    'common.includes': '包含',
    'common.category': '类别',
    'common.author': '作者',
    'common.date': '日期'
  },
  JP: {
    'nav.home': 'ホーム',
    'nav.about': '概要',
    'nav.treatments': '治療',
    'nav.event': 'イベント',
    'nav.contact': 'お問い合わせ',
    'nav.book': '予約',
    'nav.dashboard': 'ダッシュボード',
    'nav.services': 'サービス',
    'footer.copyright': '© 2024 SoRa Clinic. 全著作権所有。',
    'footer.description': '美しさのための最高の選択',
    'home.hero.title': 'SoRa Clinicへようこそ',
    'home.hero.subtitle': 'あなたの美しさのための専門的なケア',
    'home.hero.bookNow': '今すぐ予約',
    'about.title': 'SoRa Clinicについて',
    'about.subtitle': '私たちは、本物のガラス肌体験をお届けすることに情熱を注ぐK-ビューティー専門家です。韓国スキンケア伝統における長年の専門知識と卓越性への取り組みにより、すべての治療を特別なものにしています。',
    'about.journey.title': '私たちのビューティージャーニー',
    'about.team.title': 'ビューティー専門家をご紹介',
    'about.timeline.2018.title': 'SoRa Clinic設立',
    'about.timeline.2018.desc': 'SoRa Clinicは、本物のK-ビューティー治療をグローバルクライアントに提供するというビジョンで設立されました。',
    'about.timeline.2019.title': '初回ガラス肌治療',
    'about.timeline.2019.desc': '韓国ビューティー基準を国際的に先駆ける私たちのシグネチャーガラス肌治療を導入しました。',
    'about.timeline.2020.title': 'ビューティーイノベーション',
    'about.timeline.2020.desc': 'パンデミック中にホームスキンケアコンサルテーションに焦点を当てた高度な保湿療法を開発しました。',
    'about.timeline.2022.title': 'チーム拡大',
    'about.timeline.2022.desc': '専門K-ビューティー専門家を含むチームを拡大し、江南フラッグシップクリニックをオープンしました。',
    'about.timeline.2024.title': 'グローバル認知',
    'about.timeline.2024.desc': '"最高のK-ビューティークリニック"賞を受賞し、シグネチャー治療を国際的に拡張しました。',
    'treatments.title': '治療サービス',
    'treatments.subtitle': 'SoRa Clinic専門家による専門K-ビューティー治療、スキンケアソリューション、専門サービス',
    'treatments.post1.title': '究極のK-ビューティールーティン：ガラス肌への10ステップ',
    'treatments.post1.excerpt': '伝統的なK-ビューティー方法を通じて憧れのガラス肌グローを達成する包括的ガイドで韓国スキンケアの秘密を発見しましょう。',
    'treatments.post2.title': 'ガラス肌vsデューイ肌：違いを理解する',
    'treatments.post2.excerpt': 'ガラス肌とデューイ肌のニュアンスについて学び、どの韓国ビューティートレンドがあなたの肌タイプと目標に適しているかを発見しましょう。',
    'treatments.post3.title': '保湿ヒーロー：乾燥肌のための最高の韓国成分',
    'treatments.post3.excerpt': 'ヒアルロン酸からスネイルムチンまで、深い保湿のための最も効果的な韓国スキンケア成分を探求しましょう。',
    'treatments.post4.title': '季節別スキンケア：K-ビューティールーティンの適応',
    'treatments.post4.excerpt': 'すべての季節で健康で輝く肌を維持するために、年間を通じて韓国スキンケアルーティンを修正する方法を学びましょう。',
    'treatments.post5.title': 'K-ビューティーの科学：韓国スキンケアが効果的な理由',
    'treatments.post5.excerpt': '成分革新からレイヤリング技術まで、韓国スキンケアを非常に効果的にする科学的原理を深く掘り下げましょう。',
    'treatments.post6.title': 'K-ビューティーでアンチエイジング：予防vs矯正ケア',
    'treatments.post6.excerpt': '韓国式アンチエイジングスキンケアアプローチを理解し、既存の問題を治療しながら老化の兆候を防ぐ方法を学びましょう。',
    'event.title': 'イベント＆プロモーション',
    'event.subtitle': 'SoRa Clinicの特別プロモーションとイベントをご確認ください',
    'event.promo1.title': 'レーザー脱毛パッケージ',
    'event.promo1.desc': '国際患者のための完全なレーザー脱毛パッケージ。保証された滑らかで美しい肌の結果のためのプレミアムIPL技術。',
    'event.promo2.title': 'ボトックスアンチエイジング治療',
    'event.promo2.desc': '若くてしわのない肌のための専門ボトックス治療。経験豊富な韓国美容医師によるFDA承認製品。',
    'event.promo3.title': 'デルマルフィラーエンハンスメント',
    'event.promo3.desc': '自然な韓国ビューティー結果のための顔の輪郭とボリューム復元のためのプレミアムヒアルロン酸フィラー。',
    'event.promo4.title': 'ガラス肌フェイシャルパッケージ',
    'event.promo4.desc': '磁器のような肌色を達成するのに完璧な私たちのシグネチャー保湿フェイシャル治療で有名な韓国"ガラス肌"ルックを達成しましょう。',
    'event.promo5.title': 'K-ビューティーグロー治療',
    'event.promo5.desc': '輝く肌のためのLED療法、ビタミンC注入、韓国ブライトニング技術を組み合わせた包括的なK-ビューティーグロープログラム。',
    'event.promo6.title': 'プレミアムスキンケアルーティン',
    'event.promo6.desc': '包括的な肌の変容とアンチエイジングのための複数の高度な治療を組み合わせた究極の韓国ビューティーパッケージ。',
    'event.promo7.title': '保湿ビューティーブースト',
    'event.promo7.desc': '深い保湿と弾力性回復のための高度な保湿療法。',
    'contact.title': 'お問い合わせ',
    'contact.address': '住所',
    'contact.phone': '電話番号',
    'contact.email': 'メールアドレス',
    'contact.hours': '営業時間',
    'booking.title': '予約',
    'booking.name': 'お名前',
    'booking.phone': '電話番号',
    'booking.email': 'メールアドレス',
    'booking.date': '予約日',
    'booking.time': '予約時間',
    'booking.service': 'サービス選択',
    'booking.submit': '予約送信',
    'language.select': '言語選択',
    'common.readMore': '続きを読む',
    'common.learnMore': '詳しく見る',
    'common.bookNow': '今すぐ予約',
    'common.validUntil': '有効期限',
    'common.includes': '含まれるもの',
    'common.category': 'カテゴリ',
    'common.author': '著者',
    'common.date': '日付'
  }
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [currentLanguage, setCurrentLanguage] = useState<Language>(languages[0]);

  const setLanguage = (language: Language) => {
    setCurrentLanguage(language);
    // 로컬 스토리지에 저장하여 새로고침 시에도 유지
    localStorage.setItem('selectedLanguage', JSON.stringify(language));
  };

  // 번역 함수
  const t = (key: string): string => {
    const langCode = currentLanguage.code as keyof typeof translations;
    return translations[langCode]?.[key] || key;
  };

  // 컴포넌트 마운트 시 로컬 스토리지에서 언어 설정 복원
  React.useEffect(() => {
    const savedLanguage = localStorage.getItem('selectedLanguage');
    if (savedLanguage) {
      try {
        const parsed = JSON.parse(savedLanguage);
        if (languages.find(lang => lang.code === parsed.code)) {
          setCurrentLanguage(parsed);
        }
      } catch (error) {
        console.error('Failed to parse saved language:', error);
      }
    }
  }, []);

  return (
    <LanguageContext.Provider value={{ currentLanguage, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

